Bug fix signin
ColbyMainard/DevHub pull request #40
Opened 2021-04-23 13:53 UTC by raghudv94

**Disclaimer: Major changes made.. Needs Extensive Testing and verification. Also, run cucumber tests locally in your system as well. If the error is related to webpacker, run the following command: "bundle exec rails webpacker:install"**

Bug Fixes for the following feature:

1. Markup:
  Handled empty post description in a post
2. Logout:
  Cleared the username field in the session as well while logging out
3. Upvote Post:
  Merged the hyperlink and count number to the "font awesome thumbs up/down" icon
4. Delete Post:
  Fixed a failing scenario where once a vote was made, posts were not getting deleted
5. Cucumber add user test feature

Added Bootstrap CSS and JS
Added Nav bar for all pages
Note: Made changes to layout by adding bootstrap. We can discuss more on this in our next discussion

2021-04-23 17:55 UTC, ColbyMainard requested changes
Looks mostly good, but there seems to be an error in one of the cucumber tests.  Specifically, there seems to be an issue with the "Then I should have successfully logged in as a new user" step in the "I attempt to fill in every input in the form" scenario.  Please get this story passing.

2021-04-24 14:23 UTC, raghudv94 commented
@ColbyMainard I see that the cucumber user story mentioned in passing in my local system. I have already made the changes accordingly in the commit named: "Modified add user test feature to pass the test after adding navbar"

Am I missing something here?

2021-04-24 15:40 UTC, ColbyMainard commented
> @ColbyMainard I see that the cucumber user story mentioned is passing in my local system. I have already made the changes accordingly in the commit named: "Modified add user test feature to pass the test after adding navbar"
> 
> Am I missing something here?

Just re-tested and it seems to be working.  Will handle merge conflicts and merge with main.

2021-04-24 15:47 UTC, ColbyMainard approved these changes

2021-04-24 15:47 UTC, merged